name: Benchmark Hash Collections
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

concurrency:
  group: bench-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  runBenchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
